package com.craftinginterpreters.lox;

enum TokenType {
  LEFT_PAREN, RIGHT_PAREN,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
  QUESTION, COLON,

  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,

  IDENTIFIER, STRING, NUMBER,
  TRUE, FALSE, NIL,
  EOF
}
